---
version: '3.7'

services:

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      frontend-internetnz:
      backend-internetnz:

  scheme:
    build:
      context: ../inz-demo/
      dockerfile: ../irma-setup/Dockerfile.scheme.Dockerfile
    volumes:
      - ../inz-demo/inz-demo:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=irma-scheme.local.internetnz.nz
      - VIRTUAL_PORT=80
    networks:
      frontend-internetnz:

  irmago:
    build:
      context: ../
      dockerfile: ./irma-setup/Dockerfile.irmago.Dockerfile
    command: ["wait-for-it", "$SCHEME_SITE_URL/description.xml", "--", "irma", "server"]
    volumes:
      - ./build/irmago/jwtkeys:/irma/jwtkeys:cached
      - ../inz-demo/inz-demo:/irma/schemes/inz-demo:cached
      - ./certs:/etc/ssl/certs
    environment:
      - VIRTUAL_HOST=irmago.local.internetnz.nz
      - VIRTUAL_PORT=8088
    env_file:
      - .env.sample
      - .env
    ports:
      - '8088:8088'
    extra_hosts:
      - irma-scheme.local.internetnz.nz:192.168.0.10
    depends_on:
      - scheme
      - proxy
    networks:
      backend-internetnz:
        aliases:
          - irmago.local.internetnz.nz

networks:
  backend-internetnz:
  frontend-internetnz:
