---
version: '3.8'

services:

  irmago:
    build:
      context: ../inz-demo/
      dockerfile: ../irma-setup/Dockerfile.irmago.Dockerfile
    command: irma server --no-tls -s /irma/inz-demo -u http://0.0.0.0:8088/ -vvvvv
    volumes:
      - ./build/irmago/irmaserver.yaml:/etc/irmaserver/irmaserver.yaml
      - ../inz-demo/inz-demo:/irma/inz-demo
    ports:
      - '8088'
    depends_on:
      - scheme
      #- proxy
    networks:
      internetnz:

  scheme:
    build:
      context: ../inz-demo
      dockerfile: ../irma-setup/Dockerfile.scheme.Dockerfile
    volumes:
      - ../inz-demo/inz-demo:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=irma-scheme.local.internetnz.nz
      - VIRTUAL_PORT=80
    depends_on:
      - proxy
    networks:
      internetnz:
        aliases:
          - irma-scheme.local.internetnz.nz

  proxy:
    networks:
      internetnz:
        aliases:
          - irma-scheme.local.internetnz.nz

networks:
  internetnz:
