---
version: '3.7'

services:

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      frontend-internetnz:
        aliases:
          - irma-demoui.local.internetnz.nz
      backend-internetnz:

  scheme:
    build:
      context: ../inz-demo/
      dockerfile: ../irma-setup/Dockerfile.scheme.Dockerfile
    volumes:
      - ./inz-demo:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=irma-scheme.local.internetnz.nz
      - VIRTUAL_PORT=80
    networks:
      frontend-internetnz:

  irma-cli:
    build:
      context: .
      dockerfile: Dockerfile.irma.Dockerfile
    volumes:
      - ../inz-demo/inz-demo:/irma/inz-demo
    networks:
      backend-internetnz:

  irmago:
    build:
      context: ../
      dockerfile: ./irma-setup/Dockerfile.irmago.Dockerfile
    command: ["wait-for-it", "irma-scheme.local.internetnz.nz:80", "--", "irma", "server"]
    volumes:
      #- ./certs:/etc/ssl/certs:cached
      - ./build/irmago/jwtkeys:/irma/jwtkeys:cached
      - ../inz-demo/inz-demo:/irma/schemes/inz-demo:cached
    environment:
      - VIRTUAL_HOST=irmago.local.internetnz.nz
      - VIRTUAL_PORT=8088
      #- IRMASERVER_NO_TLS=true
      #- IRMASERVER_SCHEMES_PATH=/irma/schemes
      #- IRMASERVER_URL=http://13.54.7.159:8088
      #- IRMASERVER_NO_AUTH=false
      #- IRMASERVER_REQUESTORS={"keyshare_server":{"auth_method":"publickey","key_file":"/irma/jwtkeys/pk.pem"},"site":{"auth_method":"publickey","key_file":"/irma/jwtkeys/pk.pem"}}
      #- IRMASERVER_REQUESTORS='{}'
      #- IRMASERVER_VERBOSE=2
    env_file:
      # - .env.sample
      - .env
    ports:
      - '8088:8088'
    depends_on:
      - scheme
      - proxy
    networks:
      backend-internetnz:
        aliases:
          - irmago.local.internetnz.nz

networks:
  backend-internetnz:
  frontend-internetnz:
