---
version: '3.8'

services:

  scheme:
    build:
      context: ../inz-demo
      dockerfile: ../irma-setup/Dockerfile.scheme.Dockerfile
    volumes:
      - ../inz-demo/inz-demo:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=irma-scheme.local.internetnz.nz
      - VIRTUAL_PORT=80
    depends_on:
      - proxy
    networks:
      internetnz:
        aliases:
          - irma-scheme.local.internetnz.nz

  proxy:
    networks:
      internetnz:
        aliases:
          - irma-scheme.local.internetnz.nz

networks:
  internetnz:
