---
version: '3.8'

services:

  demoui:
    build:
      context: ../irma-demo-ui
      dockerfile: ../irma-setup/Dockerfile.demoui.Dockerfile
    volumes:
      - ../irma-demo-ui/:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=irma-demoui.local.internetnz.nz
      - VIRTUAL_PORT=80
    networks:
      frontend-internetnz:
        aliases:
          - irma-demoui.local.internetnz.nz

networks:
  frontend-internetnz:
