---
version: '3.8'

services:

  irmago:
    build:
      context: ../inz-demo/
      dockerfile: ../irma-setup/Dockerfile.irmago.Dockerfile
    volumes:
      - ../inz-demo/src:/irma/inz-demo
    ports:
      - '8088'
    networks:
      internetnz:

networks:
  internetnz:
