---
version: '3.8'

services:

  irmago:
    build:
      context: ../inz-demo/
      dockerfile: ../irma-setup/Dockerfile.irmago.Dockerfile
    command: ["wait-for-it", "irma-scheme.local.internetnz.nz:80", "--", "irma", "server", "--no-tls", "-u", "http://0.0.0.0:8088/", "-vv"]
    volumes:
      #- ./build/irmago/irmaserver.yaml:/etc/irmaserver/irmaserver.yaml
      - ./certs:/etc/ssl/certs:cached
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it
      - ../inz-demo/inz-demo:/irma/inz-demo
      - ../inz-demo/inz-demo:/root/.local/share/irma/irma_configuration/inz-demo
    ports:
      - '8088:8088'
    depends_on:
      - scheme
      - proxy
    networks:
      internetnz:
        aliases:
          - irmago.local.internetnz.nz

  proxy:
    networks:
      internetnz:
        aliases:
          - irma-scheme.local.internetnz.nz

networks:
  internetnz:
