---
version: '3.7'

services:

  mail:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      backend-internetnz:

  db:
    image: mysql
    restart: always
    volumes:
      - ../irma_keyshare_server/src/main/resources/database.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_USER: irma
      MYSQL_PASSWORD: irma
      MYSQL_ROOT_PASSWORD: irma
      MYSQL_DATABASE: irma_keyshare
    networks:
      backend-internetnz:
        aliases:
          - db.local.internetnz.nz

  keyshare:
    build:
      context: ../
      dockerfile: ./irma-setup/Dockerfile.keyshare.Dockerfile
    volumes:
      - ../irma_keyshare_server/src:/app/src
      - ../inz-demo/inz-demo:/app/src/main/resources/irma_configuration/inz-demo
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=irma-keyshare.local.internetnz.nz
      - VIRTUAL_PORT=8080
    networks:
      backend-internetnz:
        aliases:
          - irma-keyshare.local.internetnz.nz

networks:
  backend-internetnz:
