---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-claim
  #labels:
  #  app.kubernetes.io/instance: keyshare
spec:
  storageClassName: gp2 # for AWS EBS
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
