apiVersion: v1
kind: Service
metadata:
  name: {{ include "db.fullname" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: mysql
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/instance: keyshare
